### ISSUE TITLE
decomposition_sld generates array with useless row numbers

### ISSUE THREAD

**Issue by caranha** [fcampelo/MOEADr#1]
Not sure if this is a problem or not, but the row names of the weight array returned by decomposition_sld is meaningless (side effect of rbind, probably).

You can fix this with `rownames(X) <- NULL` if necessary

**Example**

% p <- list(H=4,.nobj=3)
% decomposition_sld(p)

   Var1 Var2 VarLast
1  0.00 0.00    1.00
2  0.25 0.00    0.75
3  0.50 0.00    0.50
4  0.75 0.00    0.25
5  1.00 0.00    0.00
6  0.00 0.25    0.75
7  0.25 0.25    0.50
8  0.50 0.25    0.25
**9  0.75 0.25    0.00
11 0.00 0.50    0.50**
12 0.25 0.50    0.25
13 0.50 0.50    0.00
16 0.00 0.75    0.25
17 0.25 0.75    0.00
21 0.00 1.00    0.00

**Comment by fcampelo** [comment]
{Var1 ... VarN} is a side effect of expand.grid, but is completely harmless in this case. Not sure if it's worth the effort of removing the names.

The name of the last column (VarLast) is used to filter the valid weight vectors.

**Comment by caranha** [comment]
Just to make sure: I'm talking about row names, not column names.

**Comment by fcampelo** [comment]
I misread, my bad. 
All the same, I think there is no harm in having the (spurious) row names. Not sure if using `rownames(X) <- NULL` would improve processing time, or even save much memory. What do you think?

**Comment by caranha** [comment]
Well, it looks weird, and the fix is a single line. It's not so much about
saving processing time, it is more about making things tidy.

That said, I don't really have a strong opinion on it, else it this would
be a bug report :-)

**Comment by fcampelo** [comment]
Tidy is good in my book. :-)
Please go ahead and add the `rownames(W) <- NULL` line in your next commit.
:-)

Cheers,

---
Prof. Felipe Campelo, Ph.D.
Operations Research and Complex Systems Laboratory - ORCS Lab
Dept. Electrical Engineering, Universidade Federal de Minas Gerais
Belo Horizonte, Brazil.
http://orcslab.cpdee.ufmg.br
Tel.: (+ 55 31) 3409-3421
Fax: (+ 55 31) 3409-4810

**Comment by caranha** [comment]
Okie dokie
