### ISSUE TITLE
Add "devel" branch

### ISSUE THREAD

**Issue by fcampelo** [fcampelo/MOEADr#3]
I think we should add a "devel" branch. The idea would be for one of us to commit changes to "devel" first, then move to "master" after the commit is checked by another developer (currently its just two of us, but hopefully others will join us in the future). 

Whatcha think?

**Comment by caranha** [comment]
I think it would be faster to discuss this on gtalk or skype. But my general idea is that this will be necessary when we have a usable beta out, but not necessary right now.

My current workflow with github is more or less like this at the moment:
- Open a new branch for a specific feature. 
- Implement the feature until it passes all tests
- (for this project): Update master from your repository
- Merge back into master
- (for this project): Send a pull request from my master into yours

I imagine that we will replace master with devel once we have a beta, but I don't see the need right now :-)

**Comment by fcampelo** [comment]
Agreed!
