### ISSUE TITLE
Size of Decomposition Matrix on "writing-functions for moeadr"

### ISSUE THREAD

**Issue by caranha** [fcampelo/MOEADr#4]
So, looking at the documentation at "writing functions", I noticed that the return value for Decomposition Strategies states that:

`the function must output a _N x m_ matrix of weights, with _N_ the population size and _m_ the number of objectives.`

This is not true for SLD, MSLD, or Uniform, both in the paper, and in the code. For all these three, "N" is he number of sub problems calculated by the decomposition method based on the user parameters, which (I guess) should be <= population size, but not necessarily equal to population size.

Is the documentation wrong, or the code wrong?

**Comment by fcampelo** [comment]
The documentation is incorrect: where you read "population size" please replace by "number of subproblems" (which may or may not be equal to the population size, although it usually is).

I'll correct the documentation right away.

Cheers
