### ISSUE TITLE
Implement Scalarization Strategies

### ISSUE THREAD

**Issue by caranha** [fcampelo/MOEADr#7]
Implement the missing scalarization strategies

- [x] ws is just multiplying the matrixes, without subtracting the min
- [x] wt is actually ws, without the Tchebycheff norm
- [x] awt is missing
- [x] double check pbi calculations (seems to be missing a norm division in D2)

Also, all scalarization functions seem to be missing the min step which is included in the paper.

**Comment by caranha** [comment]
Hmmm, I forgot to protect the AWT from div/0. Will try to sneak that in today.

**Comment by caranha** [comment]
HmHMmm.... The calculation of rho in AWT (page 4) requires the inverse of the weights, which means we need to deal with weights with zero values.

If we just add an epson to the zero values, the resulting Rho will be quite extreme. Example:

Weight Matrix:
0 0.25 0.25 0.25 0.25
0 0.25 0.25 0.25 0.25
0 0.5 0.125 0.25 0.125
0 0.125 0.125 0.25 0.5

Rho:
1 0 0 0 0
1 0 0 0 0
1 0 0 0 0
1 0 0 0 0

Is this acceptable?

**Comment by fcampelo** [comment]
I believe it is. I'll consult Lucas about it, but from my understanding that should be the expected behavior - it certainly the is if we use an asymptotic argument.
